
pipeline {
    agent any
    stages {
        stage('Init') {
            steps {
                script{
                    def dockerPath = tool 'docker' //全局配置里的docker
                    env.PATH = "${dockerPath}/bin:${env.PATH}" //添加了系统环境变量上
                }
            }
        }
        stage('Build') {
            steps {
                script{
                    sh "docker build --rm -t ${params.imageName}:${params.version}  -f deploy/Dockerfile ."
                }
            }
        }
        stage('Deploy') {
            steps {
                script{
                    sh "docker login -u djlxs -p djl.l951753" 
                    sh "docker tag ${params.imageName}:${params.version} djlxs/${params.imageName}:${params.version}" 
                    sh "docker push djlxs/${params.imageName}:${params.version}"
                    sh "kubectl apply -f deploy/k8s/app-deployment.yaml"
                    sh "kubectl apply -f deploy/k8s/app-service.yaml"
                    sh "kubectl apply -f deploy/k8s/app-ingress.yaml"
                }
            }
        }
    }
}