
pipeline {
    agent any
    stages {
        stage('Init') {
            steps {
                script{
                    def dockerPath = tool 'docker' //全局配置里的docker
                    env.PATH = "${dockerPath}/bin:${env.PATH}" //添加了系统环境变量上
                }
            }
        }
        stage('Test') {
            steps {
                script{
                    echo 'just a test'
                }
            }
        }
    }
}